name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    inputs:
      test_branch:
        description: 'Branch to test'
        required: false

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    # コードのチェックアウト
    - name: Checkout code
      uses: actions/checkout@v3

    # Pythonのセットアップ
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'

    # 依存関係のインストール
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # テストの実行
    - name: Run tests
      run: |
        python -m unittest discover -s tests -p "test_*.py"